### ISSUE TITLE
300 Multiple Choices

### ISSUE THREAD

**Issue by manakill** [aquametalabs/aquameta#176]
When I logout and re-login I get an error 300 Multiple Choices page.
I go to /dev and then it loads fine

I also noticed when logged out that localhost/ is Forbidden and then when I navigate to /login that works fine. Maybe have the login page be the default page loaded on logout?

**Comment by erichanson** [comment]
The 300 means there are two resources that both are matching the path requested, in this case `/`.  This is because when that older version of the IDE was installed, it had a different resource at path `/`, which is now deleted abut wasn't deleted by the checkout.  You can fix it by going into any bundle, clicking the "untracked rows" tab and then finding the endpoint.resource with path `/`, checking it and clicking delete.

Points to an underlying issue that `bundle.checkout()` should delete from the working copy any rows that were deleted from the bundle.  And good idea about making `/login` more obvious.  Will make some issues.  Thanks.

**Comment by manakill** [comment]
Deleting that endpoint.resource /  worked for me. Thanks!
