### ISSUE TITLE
Support event subscriptions in REST requests

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#21]
Launch sequence for Endpoint client via datum.js:

1. Instantiate AQ.Database instance, passing in url and settings object.
2. If settings.evented = true or try, attempt to open up a websocket connection to the database.  On connection success, initiate handshake sequence and receive a event session_id (different from a auth session, which should have already happened if relevant).  On connection failure, set self.evented to false.
3. For future REST requests, if this db instance is 'evented' and the request is evented, pass in the event session to the REST server as part of the request on the URL or POST vars
4. REST handler does a session_attach() to the supplied session_id if the request is evented, and issues the appropriate subscribe_*().
5. Upon receipt of the event, client is responsible for deleting it from the events queue with another DELETE request to the event table.

**Comment by micburks** [comment]
Couple notes:
- We are only interesting in subscribing to a table/row/...etc on GET requests. I don't think any other method makes sense
- We can either create a session via endpoint call or WebSocket method. Not sure which makes more sense

**Comment by micburks** [comment]
Ran into an issue with attaching/using a session. There is a very meaningful distinction between these two things. Attaching to a session means awaiting event notifications or receiving old ones. Using a session means subscribing this session to changes on a specified database object.

HTTP requests are eventless (not persistent), so calls to endpoint.request do not need to "attach" to a session, but do need to change the connection_id of the event.session to "use" the session_id. The event session schema currently only allows for one connection to use a session at a time. This displays a false abstraction of event sessions and requires a small refactor.

All subscribe functions should take a session_id as an argument instead of using current_session_id() (which references meta.current_connection_id()). This way we can get rid of associating connections with sessions so that multiple connections can use/attach to the same session.
