### ISSUE TITLE
Stop copying aquameta source into container

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#25]
Instead use a volume to mount the source on the host inside the container and install from the volume.

**Comment by micburks** [comment]
Didn't really mean to close this issue, but it seems that this is not possible to mount a volume during build with Docker because it breaks the idea of portability. If it is really that important to not copy our source into the image, we have a few other options, possibly using a shared volume created inside the container

**Comment by erichanson** [comment]
Closing this as not really feasible.
