### ISSUE TITLE
Web semantics 

### ISSUE THREAD

**Issue by gedw99** [aquametalabs/aquameta#280]
Cool architecture @erichanson 

it’s data all the way down :) 

checkout htmx. It’s a good match to the way your web semantics works.

htmx is old school with a simple way to describe interactions whereby the web page is progressively changes using a very simple data notation.

the concepts are rooted in how your whole architect works in that your capturing the delta / diff.

There’s pls try of golang htmx examples out there and you can use SSS or WSS are your transport with zero code changes .

**Comment by erichanson** [comment]
Thanks for the feedback!

I checked out htmx, spent some time with it.  I could see how some folks would like it, but to me it feels like the product of the constraints that the file-based paradigm imposes on coders.  You don't want to have an HTML file, CSS file and JS file for each component of each page, because, files.  Aquameta very much embraces separation of concerns at the web level (and ideally everywhere else) so conflating them all together in one file feels like a step backwards.  My two cents.  Interesting stuff though.
