### ISSUE TITLE
Socket 5433 Exists But 5432 Demanded By pg_http

### ISSUE THREAD

**Issue by jabowery** [aquametalabs/aquameta#3]
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
HTTP/1.0 500 Internal Server Error
Server: pg_http
Content-Type: text/plain

could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

jabowery@jabowery-H61M-S2-B3:~/dev/aquameta/core/004-aquameta_endpoint/servers/background_worker$ sudo ls -al /var/run/postgresql
total 8
drwxrwsr-x  2 postgres postgres  100 May 21 21:42 .
drwxr-xr-x 32 root     root     1020 May 20 14:54 ..
-rw-r--r--  1 postgres postgres    6 May 21 21:42 9.4-main.pid
srwxrwxrwx  1 postgres postgres    0 May 21 21:42 .s.PGSQL.5433
-rw-------  1 postgres postgres   71 May 21 21:42 .s.PGSQL.5433.lock

jabowery@jabowery-H61M-S2-B3:~/dev/aquameta/core/004-aquameta_endpoint/servers/background_worker$ git rev-parse HEAD
f6b648891717bdb8f88eb25c8f455f329d0676cc

**Comment by erichanson** [comment]
Looks like you're running PostgreSQL on port 5433.  The PostgreSQL default port is 5432 so maybe you're running two versions of PostgreSQL at the same time?

That's fine, but then you have to change the background worker's connection settings to point to port 5433 instead of 5432 and recompile the background worker.

On this line of pg_http.c:

https://github.com/aquametalabs/aquameta/blob/master/core/004-aquameta_endpoint/servers/background_worker/pg_http.c#L93

Change it to:

conn = PQconnectdb("dbname=aquameta port=5433");

as described here:

http://www.postgresql.org/docs/8.1/static/libpq.html#LIBPQ-CONNECT

**Comment by erichanson** [comment]
I updated the README:
https://github.com/aquametalabs/aquameta/commit/5a65927025774999ea6d43d13e96431fef905b0d
